image: docker:latest

stages:
  - deploy

deploy:
  stage: deploy
  services:
    - docker:dind
  before_script:
    - apk add --no-cache aws-cli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.ap-southeast-2

  script:
    - aws s3 sync ./ s3:gitlab-to-s3-superfast-highway 
    - main
